In [2]:
#function\

def my_fuction():
    print("hello form a function")
my_fuction()

hello form a function


In [3]:
import numpy as np


In [5]:
arr=np.array([0,1,2])
arr.itemsize
arr*2

array([0, 2, 4])

In [6]:
#lets create a numpy
my_list=[1,2,3]

my_array=np.array(my_list)

my_array

array([1, 2, 3])

In [8]:
#create matrix

my_matrix=[[1,2,3],[4,5,6]]
matrix_one=np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix_one.shape

(2, 3)

Tuple er ordered ta thik korte hobe,

In [10]:
my_tuple=(-1,-3,5,2,0,1)
my_array=np.array(my_tuple)
my_array

array([-1, -3,  5,  2,  0,  1])

In [11]:
my_tuple=(-1,-3,5,2,0,1)
my_tuple

(-1, -3, 5, 2, 0, 1)

In [13]:
num=np.arange(101)
num

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [17]:
np.arange(3.01 ,10,2,dtype=float)

array([3.01, 5.01, 7.01, 9.01])

In [21]:
np.linspace(1,10,5,retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [24]:
x=np.arange(0,16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
x.shape


(16,)

In [30]:

x=x.reshape(4,4)

In [31]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
y=x.reshape(2,4,2)
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

prothom 2 ta holo koita matrix korte chai. er por er 4 ta row mean korebe r last er 2 holo koto gula colum hobe

issa moto kora jabena sob element er soman hote hobe mane duita matrix mile 16 ta element hote hobe|

In [34]:
x=np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
x.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
y=x.reshape(2,2,5)
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [41]:
x=np.arange(30)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
x.reshape(3,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [43]:
# create random value

np.random.rand(4)

array([0.65269629, 0.67720717, 0.56575453, 0.64169273])

In [44]:
np.random.rand(4,2)

array([[0.41151499, 0.75767436],
       [0.14860386, 0.26543169],
       [0.57478864, 0.5675201 ],
       [0.92322709, 0.01605535]])

In [45]:
np.random.randn(4,2)

array([[-0.74737575, -0.25326387],
       [-2.46102845,  0.15589566],
       [-0.6685153 , -0.77045375],
       [-0.75404211, -1.32396135]])

ekhan a randn a j man gula asbe ogula normal distribution kore value dibe

In [47]:
np.random.randint(100,200,5)

array([151, 109, 150, 153, 199])

random akare int value dibe

In [48]:
arr.arange=np.arange.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

Sliceing and indexing in array porte hobe. egla age thekei jana

Sliceing and indexing in array porte hobe 2D ba matrix er kaj korte parbe. egla age thekei jana

###Broadcasting kora
jegukuno mathmatical operation sob gula value opor e korbe eita k broadcasting bole

np.ones(4,4) 

matrix er jog kora jai 

arrayer  sob kisu kora jai broadcasting



arrithmactical sob kisu array dia kora (+,-,*,/)
