In [10]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import datasets
import seaborn as sns



# Overview of machine learning

In [6]:
#Overview of machine learning

data= sns.load_dataset("iris")

data.head(20)
#print(data.shape)

sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa

In [9]:
# machine learing er niom hosse age seta k data dia bujate hoi sekhano hoi
##jeta k classyfy korte hobe seta k label bole
### last er kolam tar class ace 3 ta r koto gula feature ace seta k sample bole
####

data= sns.load_dataset("iris")

print(data.shape)
data.head()

(150, 5)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
#1.yes and no bainary classification
#32. 2 er odhik hole seta k multiclassifiacton problem jodi calssification finit number a kora jai 
### diabestics er level regression problem jekhn a level infinite 
#### supervised jodi age theke bole dei j eita ki pore se classified kora jai 
### unsupervised joid age theke janan na dei j eita kmn hobe kintu cluster kora thake jekhn thke pore bujte pare

# Machine learning a input r output dewa hoi se rules sikhe nei

# cross validation, 3/4 deta babohar kora hoi training er jonno r 1/4 ongso testing er jonno


# Introduction to key concepts(Feature,labels,traning,testing)

In [3]:
indx_train=int(0.8*len(data))
data_train=data.iloc[0:indx_train, :]
test_feature=data.iloc[0:indx_train:,0:4]
test_label=data.iloc[indx_train:,4]

In [4]:
data_train=data.iloc[0:indx_train, :]
test_feature=data.iloc[0:indx_train:,0:4]
test_label=data.iloc[indx_train:,4]

In [3]:
#test_label

In [14]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import datasets
import seaborn as sns

In [16]:
X,y = datasets.load_iris(return_X_y = True)
X.shape,y.shape

((150, 4), (150,))

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [18]:
classifier_1= svm.SVC().fit(X_train,y_train)
predicted_label=classifier_1.predict(X_test)

In [19]:
predicted_label

array([0, 1, 1, 0, 2, 0, 0, 2, 1, 2, 0, 1, 1, 1, 1, 0, 0, 1, 2, 2, 2, 1,
       0, 1, 2, 1, 1, 0, 0, 0])

In [20]:
print(predicted_label)
print(y_test)

[0 1 1 0 2 0 0 2 1 2 0 1 1 1 1 0 0 1 2 2 2 1 0 1 2 1 1 0 0 0]
[0 1 1 0 2 0 0 2 2 2 0 1 1 1 2 0 0 1 2 2 2 1 0 1 2 1 1 0 0 0]


In [22]:
Accurracy_model=classifier_1.score(X_test,y_test)
print(Accurracy_model) 
## acuracy level

0.9333333333333333


In [ ]:
## kagel ba bithub theke choto choto project korte hobe

# KNN ,LDA ,Random forest, Ann, Deep learning model